spring.application.name=lms
spring.datasource.url=jdbc:postgresql://localhost:5432/lms_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.hibernate.show-sql=true

#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.postgreSQLDialect